// Code generated by Kitex v0.15.0. DO NOT EDIT.

package core_api

import (
	"context"

	"github.com/cloudwego/kitex/pkg/streaming"
)

type CoreApi interface {
	Completions(req *CompletionsReq, stream CoreApi_CompletionsServer) (err error)
	CreateConversation(ctx context.Context, req *CreateConversationReq) (res *CreateConversationResp, err error)
	ListConversation(ctx context.Context, req *ListConversationReq) (res *ListConversationResp, err error)
	GetConversation(ctx context.Context, req *GetConversationReq) (res *GetConversationResp, err error)
	Generate(ctx context.Context, req *GenerateBriefReq) (res *GenerateBriefResp, err error)
	RenameConversation(ctx context.Context, req *RenameConversationReq) (res *RenameConversationResp, err error)
	DeleteConversation(ctx context.Context, req *DeleteConversationReq) (res *DeleteConversationResp, err error)
	SearchConversation(ctx context.Context, req *SearchConversationReq) (res *SearchConversationResp, err error)
	ListAgents(ctx context.Context, req *ListAgentsReq) (res *ListAgentsResp, err error)
	Feedback(ctx context.Context, req *FeedbackReq) (res *FeedbackResp, err error)
}

type CoreApi_CompletionsServer interface {
	streaming.Stream
	Send(*SSEEvent) error
}
