// Code generated by Kitex v0.15.2. DO NOT EDIT.

package manageapi

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	manage "github.com/xh-polaris/innospark-idl/kitex_gen/manage"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AdminLogin(ctx context.Context, Req *manage.AdminLoginReq, callOptions ...callopt.Option) (r *manage.AdminLoginResp, err error)
	ListUser(ctx context.Context, Req *manage.ListUserReq, callOptions ...callopt.Option) (r *manage.ListUserResp, err error)
	Forbidden(ctx context.Context, Req *manage.ForbiddenUserReq, callOptions ...callopt.Option) (r *manage.ForbiddenUserResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kManageApiClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kManageApiClient struct {
	*kClient
}

func (p *kManageApiClient) AdminLogin(ctx context.Context, Req *manage.AdminLoginReq, callOptions ...callopt.Option) (r *manage.AdminLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminLogin(ctx, Req)
}

func (p *kManageApiClient) ListUser(ctx context.Context, Req *manage.ListUserReq, callOptions ...callopt.Option) (r *manage.ListUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUser(ctx, Req)
}

func (p *kManageApiClient) Forbidden(ctx context.Context, Req *manage.ForbiddenUserReq, callOptions ...callopt.Option) (r *manage.ForbiddenUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Forbidden(ctx, Req)
}
