// Code generated by Kitex v0.15.2. DO NOT EDIT.

package systemapi

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	core_api "github.com/xh-polaris/innospark-idl/kitex_gen/core_api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GenSignedURL": kitex.NewMethodInfo(
		genSignedURLHandler,
		newGenSignedURLArgs,
		newGenSignedURLResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	systemApiServiceInfo                = NewServiceInfo()
	systemApiServiceInfoForClient       = NewServiceInfoForClient()
	systemApiServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return systemApiServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return systemApiServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return systemApiServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SystemApi"
	handlerType := (*core_api.SystemApi)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "core_api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func genSignedURLHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.GenSignedURLReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.SystemApi).GenSignedURL(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GenSignedURLArgs:
		success, err := handler.(core_api.SystemApi).GenSignedURL(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GenSignedURLResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGenSignedURLArgs() interface{} {
	return &GenSignedURLArgs{}
}

func newGenSignedURLResult() interface{} {
	return &GenSignedURLResult{}
}

type GenSignedURLArgs struct {
	Req *core_api.GenSignedURLReq
}

func (p *GenSignedURLArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GenSignedURLArgs) Unmarshal(in []byte) error {
	msg := new(core_api.GenSignedURLReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GenSignedURLArgs_Req_DEFAULT *core_api.GenSignedURLReq

func (p *GenSignedURLArgs) GetReq() *core_api.GenSignedURLReq {
	if !p.IsSetReq() {
		return GenSignedURLArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GenSignedURLArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GenSignedURLArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GenSignedURLResult struct {
	Success *core_api.GenSignedURLResp
}

var GenSignedURLResult_Success_DEFAULT *core_api.GenSignedURLResp

func (p *GenSignedURLResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GenSignedURLResult) Unmarshal(in []byte) error {
	msg := new(core_api.GenSignedURLResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GenSignedURLResult) GetSuccess() *core_api.GenSignedURLResp {
	if !p.IsSetSuccess() {
		return GenSignedURLResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GenSignedURLResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.GenSignedURLResp)
}

func (p *GenSignedURLResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GenSignedURLResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GenSignedURL(ctx context.Context, Req *core_api.GenSignedURLReq) (r *core_api.GenSignedURLResp, err error) {
	var _args GenSignedURLArgs
	_args.Req = Req
	var _result GenSignedURLResult
	if err = p.c.Call(ctx, "GenSignedURL", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
