// Code generated by Kitex v0.14.1. DO NOT EDIT.

package basic

import "github.com/cloudwego/prutal"

type Page struct {
	Page      *int64  `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Size      *int64  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	LastToken *string `protobuf:"bytes,3,opt,name=lastToken" json:"lastToken,omitempty"`
	Backward  *bool   `protobuf:"varint,4,opt,name=backward" json:"backward,omitempty"`
	Offset    *int64  `protobuf:"varint,5,opt,name=offset" json:"offset,omitempty"`
}

func (x *Page) Reset() { *x = Page{} }

func (x *Page) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Page) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Page) GetPage() int64 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *Page) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *Page) GetLastToken() string {
	if x != nil && x.LastToken != nil {
		return *x.LastToken
	}
	return ""
}

func (x *Page) GetBackward() bool {
	if x != nil && x.Backward != nil {
		return *x.Backward
	}
	return false
}

func (x *Page) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}
