// Code generated by Kitex v0.14.1. DO NOT EDIT.

package basic

import "github.com/cloudwego/prutal"

type Page struct {
	Page   *int64  `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`    // 页面数
	Size   *int64  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`    // 页面大小
	Cursor *string `protobuf:"bytes,3,opt,name=cursor" json:"cursor,omitempty"` // 最后一个游标
}

func (x *Page) Reset() { *x = Page{} }

func (x *Page) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Page) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Page) GetPage() int64 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *Page) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *Page) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}
